/*
The following sources were used as a template for the following model.
***************************************************************************************//*

*    Title: MiniFilm-node-auth source codev
*    Author: Sotiriadis, S
*    Date: 2022
*    Code version: 2022
*    Availability: https://github.com/steliosot/MiniFilm-node-auth/blob/master/models/Film.js
*
***************************************************************************************//*
(Version 2022) [Source code]. https://github.com/steliosot/MiniFilm-node-auth/blob/master/models/Film.js

*/


const mongoose = require('mongoose')
const Comment = require('./Comment')

const ThoughtSchema = mongoose.Schema({
    //ID will be automatically generated by MongoDB
    "title":{
        type:String,
        required:true
    },
    "timestamp":{
        type:Date,
        default:Date.now
    }
    ,
    "thinker":{
        type:String,
        required:true
    },

    "description":{
        type:String,
        required:true
    },
    "detail":{
        type:String,
        required:true
    },
    "echoChamber":{
        type:String,
        required:true
    },
    "score":{
        type:Number,
        default:0
    },
    "image":{
        type:String,
        required:true
    },
    "comments":[{
        type:mongoose.Schema.Types.ObjectId,
        ref: "Comments"

    }]
})

const thought_model = mongoose.model('Thoughts',ThoughtSchema)
const test_thought_model = mongoose.model('_test_thoughts',ThoughtSchema)
module.exports = { ThoughtModel: thought_model, TestThoughtModel: test_thought_model }